export const FORM_TEXT_FIELD_DEFAULT_MIN_LEN = 3
export const FORM_TEXT_FIELD_DEFAULT_MAX_LEN = 40
export const FORM_DESCRIPTION_FIELD_MIN_LEN = 1
export const FORM_DESCRIPTION_FIELD_MAX_LEN = 255

export const FORM_FOOTPRINT_TEXT_FIELD_MAX_LEN = 30
export const FORM_FOOTPRINT_DESCRIPTION_FIELD_MAX_LEN = 200
