export const ADD_EDIT_NETWORK = 'NetworkFormContainer'
export const ADD_EDIT_GROUP = 'GroupFormContainer'
export const ADD_EDIT_POP = 'PopFormContainer'
export const ADD_EDIT_POD = 'PodFormContainer'
export const ADD_NODE = 'AddNodeContainer'
export const EDIT_NODE = 'EditNodeContainer'
export const ADD_EDIT_ACCOUNT = 'AccountFormContainer'
