export const TIME_ZONES = {
  'Africa': [
    {'label': 'Ouagadougou', 'value': 'Africa/Ouagadougou'},
    {'label': 'Bujumbura', 'value': 'Africa/Bujumbura'},
    {'label': 'Porto-Novo', 'value': 'Africa/Porto-Novo'},
    {'label': 'Gaborone', 'value': 'Africa/Gaborone'},
    {'label': 'Kigali', 'value': 'Africa/Kigali'},
    {'label': 'Bissau', 'value': 'Africa/Bissau'},
    {'label': 'Malabo', 'value': 'Africa/Malabo'},
    {'label': 'Libreville', 'value': 'Africa/Libreville'},
    {'label': 'Conakry', 'value': 'Africa/Conakry'},
    {'label': 'Banjul', 'value': 'Africa/Banjul'},
    {'label': 'Accra', 'value': 'Africa/Accra'},
    {'label': 'Tunis', 'value': 'Africa/Tunis'},
    {'label': 'Lusaka', 'value': 'Africa/Lusaka'},
    {'label': 'El Aaiun', 'value': 'Africa/El_Aaiun'},
    {'label': 'Cairo', 'value': 'Africa/Cairo'},
    {'label': 'Johannesburg', 'value': 'Africa/Johannesburg'},
    {'label': 'Addis Ababa', 'value': 'Africa/Addis_Ababa'},
    {'label': 'Mogadishu', 'value': 'Africa/Mogadishu'},
    {'label': 'Harare', 'value': 'Africa/Harare'},
    {'label': 'Ceuta', 'value': 'Africa/Ceuta'},
    {'label': 'Asmara', 'value': 'Africa/Asmara'},
    {'label': 'Casablanca', 'value': 'Africa/Casablanca'},
    {'label': 'Bamako', 'value': 'Africa/Bamako'},
    {'label': 'Blantyre', 'value': 'Africa/Blantyre'},
    {'label': 'Nouakchott', 'value': 'Africa/Nouakchott'},
    {'label': 'Kampala', 'value': 'Africa/Kampala'},
    {'label': 'Dar es Salaam', 'value': 'Africa/Dar_es_Salaam'},
    {'label': 'Windhoek', 'value': 'Africa/Windhoek'},
    {'label': 'Niamey', 'value': 'Africa/Niamey'},
    {'label': 'Lagos', 'value': 'Africa/Lagos'},
    {'label': 'Abidjan', 'value': 'Africa/Abidjan'},
    {'label': 'Douala', 'value': 'Africa/Douala'},
    {'label': 'Brazzaville', 'value': 'Africa/Brazzaville'},
    {'label': 'Bangui', 'value': 'Africa/Bangui'},
    {'label': 'Kinshasa', 'value': 'Africa/Kinshasa'},
    {'label': 'Lubumbashi', 'value': 'Africa/Lubumbashi'},
    {'label': 'Mbabane', 'value': 'Africa/Mbabane'},
    {'label': 'Nairobi', 'value': 'Africa/Nairobi'},
    {'label': 'Juba', 'value': 'Africa/Juba'},
    {'label': 'Sao Tome', 'value': 'Africa/Sao_Tome'},
    {'label': 'Dakar', 'value': 'Africa/Dakar'},
    {'label': 'Freetown', 'value': 'Africa/Freetown'},
    {'label': 'Khartoum', 'value': 'Africa/Khartoum'},
    {'label': 'Djibouti', 'value': 'Africa/Djibouti'},
    {'label': 'Algiers', 'value': 'Africa/Algiers'},
    {'label': 'Monrovia', 'value': 'Africa/Monrovia'},
    {'label': 'Maseru', 'value': 'Africa/Maseru'},
    {'label': 'Lome', 'value': 'Africa/Lome'},
    {'label': 'Ndjamena', 'value': 'Africa/Ndjamena'},
    {'label': 'Tripoli', 'value': 'Africa/Tripoli'},
    {'label': 'Luanda', 'value': 'Africa/Luanda'},
    {'label': 'Maputo', 'value': 'Africa/Maputo'}
  ],
  'America': [
    {'label': 'Barbados', 'value': 'America/Barbados'},
    {'label': 'St Barthelemy', 'value': 'America/St_Barthelemy'},
    {'label': 'La Paz', 'value': 'America/La_Paz'},
    {'label': 'Jamaica', 'value': 'America/Jamaica'},
    {'label': 'Kralendijk', 'value': 'America/Kralendijk'},
    {'label': 'Noronha', 'value': 'America/Noronha'},
    {'label': 'Belem', 'value': 'America/Belem'},
    {'label': 'Fortaleza', 'value': 'America/Fortaleza'},
    {'label': 'Recife', 'value': 'America/Recife'},
    {'label': 'Araguaina', 'value': 'America/Araguaina'},
    {'label': 'Maceio', 'value': 'America/Maceio'},
    {'label': 'Bahia', 'value': 'America/Bahia'},
    {'label': 'Sao Paulo', 'value': 'America/Sao_Paulo'},
    {'label': 'Campo Grande', 'value': 'America/Campo_Grande'},
    {'label': 'Cuiaba', 'value': 'America/Cuiaba'},
    {'label': 'Santarem', 'value': 'America/Santarem'},
    {'label': 'Porto Velho', 'value': 'America/Porto_Velho'},
    {'label': 'Boa Vista', 'value': 'America/Boa_Vista'},
    {'label': 'Manaus', 'value': 'America/Manaus'},
    {'label': 'Eirunepe', 'value': 'America/Eirunepe'},
    {'label': 'Rio Branco', 'value': 'America/Rio_Branco'},
    {'label': 'Nassau', 'value': 'America/Nassau'},
    {'label': 'Belize', 'value': 'America/Belize'},
    {'label': 'Guatemala', 'value': 'America/Guatemala'},
    {'label': 'Guadeloupe', 'value': 'America/Guadeloupe'},
    {'label': 'Guyana', 'value': 'America/Guyana'},
    {'label': 'Cayenne', 'value': 'America/Cayenne'},
    {'label': 'Grenada', 'value': 'America/Grenada'},
    {'label': 'El Salvador', 'value': 'America/El_Salvador'},
    {'label': 'Godthab', 'value': 'America/Godthab'},
    {'label': 'Danmarkshavn', 'value': 'America/Danmarkshavn'},
    {'label': 'Scoresbysund', 'value': 'America/Scoresbysund'},
    {'label': 'Thule', 'value': 'America/Thule'},
    {'label': 'Port-au-Prince', 'value': 'America/Port-au-Prince'},
    {'label': 'Tegucigalpa', 'value': 'America/Tegucigalpa'},
    {'label': 'Caracas', 'value': 'America/Caracas'},
    {'label': 'Puerto Rico', 'value': 'America/Puerto_Rico'},
    {'label': 'Asuncion', 'value': 'America/Asuncion'},
    {'label': 'Panama', 'value': 'America/Panama'},
    {'label': 'Lima', 'value': 'America/Lima'},
    {'label': 'Miquelon', 'value': 'America/Miquelon'},
    {'label': 'Guayaquil', 'value': 'America/Guayaquil'},
    {'label': 'Marigot', 'value': 'America/Marigot'},
    {'label': 'Martinique', 'value': 'America/Martinique'},
    {'label': 'Montserrat', 'value': 'America/Montserrat'},
    {'label': 'Mexico City', 'value': 'America/Mexico_City'},
    {'label': 'Cancun', 'value': 'America/Cancun'},
    {'label': 'Merida', 'value': 'America/Merida'},
    {'label': 'Monterrey', 'value': 'America/Monterrey'},
    {'label': 'Matamoros', 'value': 'America/Matamoros'},
    {'label': 'Mazatlan', 'value': 'America/Mazatlan'},
    {'label': 'Chihuahua', 'value': 'America/Chihuahua'},
    {'label': 'Ojinaga', 'value': 'America/Ojinaga'},
    {'label': 'Hermosillo', 'value': 'America/Hermosillo'},
    {'label': 'Tijuana', 'value': 'America/Tijuana'},
    {'label': 'Bahia Banderas', 'value': 'America/Bahia_Banderas'},
    {'label': 'Managua', 'value': 'America/Managua'},
    {'label': 'Bogota', 'value': 'America/Bogota'},
    {'label': 'Santiago', 'value': 'America/Santiago'},
    {'label': 'St Johns', 'value': 'America/St_Johns'},
    {'label': 'Halifax', 'value': 'America/Halifax'},
    {'label': 'Glace Bay', 'value': 'America/Glace_Bay'},
    {'label': 'Moncton', 'value': 'America/Moncton'},
    {'label': 'Goose Bay', 'value': 'America/Goose_Bay'},
    {'label': 'Blanc-Sablon', 'value': 'America/Blanc-Sablon'},
    {'label': 'Toronto', 'value': 'America/Toronto'},
    {'label': 'Nipigon', 'value': 'America/Nipigon'},
    {'label': 'Thunder Bay', 'value': 'America/Thunder_Bay'},
    {'label': 'Iqaluit', 'value': 'America/Iqaluit'},
    {'label': 'Pangnirtung', 'value': 'America/Pangnirtung'},
    {'label': 'Atikokan', 'value': 'America/Atikokan'},
    {'label': 'Winnipeg', 'value': 'America/Winnipeg'},
    {'label': 'Rainy River', 'value': 'America/Rainy_River'},
    {'label': 'Resolute', 'value': 'America/Resolute'},
    {'label': 'Rankin Inlet', 'value': 'America/Rankin_Inlet'},
    {'label': 'Regina', 'value': 'America/Regina'},
    {'label': 'Swift Current', 'value': 'America/Swift_Current'},
    {'label': 'Edmonton', 'value': 'America/Edmonton'},
    {'label': 'Cambridge Bay', 'value': 'America/Cambridge_Bay'},
    {'label': 'Yellowknife', 'value': 'America/Yellowknife'},
    {'label': 'Inuvik', 'value': 'America/Inuvik'},
    {'label': 'Creston', 'value': 'America/Creston'},
    {'label': 'Dawson Creek', 'value': 'America/Dawson_Creek'},
    {'label': 'Fort Nelson', 'value': 'America/Fort_Nelson'},
    {'label': 'Vancouver', 'value': 'America/Vancouver'},
    {'label': 'Whitehorse', 'value': 'America/Whitehorse'},
    {'label': 'Dawson', 'value': 'America/Dawson'},
    {'label': 'Costa Rica', 'value': 'America/Costa_Rica'},
    {'label': 'Curacao', 'value': 'America/Curacao'},
    {'label': 'Havana', 'value': 'America/Havana'},
    {'label': 'Lower Princes', 'value': 'America/Lower_Princes'},
    {'label': 'Paramaribo', 'value': 'America/Paramaribo'},
    {'label': 'St Kitts', 'value': 'America/St_Kitts'},
    {'label': 'Cayman', 'value': 'America/Cayman'},
    {'label': 'Santo Domingo', 'value': 'America/Santo_Domingo'},
    {'label': 'Dominica', 'value': 'America/Dominica'},
    {'label': 'Tortola', 'value': 'America/Tortola'},
    {'label': 'New York', 'value': 'America/New_York'},
    {'label': 'Detroit', 'value': 'America/Detroit'},
    {'label': 'Kentucky - Louisville', 'value': 'America/Kentucky/Louisville'},
    {'label': 'Kentucky - Monticello', 'value': 'America/Kentucky/Monticello'},
    {'label': 'Indiana - Indianapolis', 'value': 'America/Indiana/Indianapolis'},
    {'label': 'Indiana - Vincennes', 'value': 'America/Indiana/Vincennes'},
    {'label': 'Indiana - Winamac', 'value': 'America/Indiana/Winamac'},
    {'label': 'Indiana - Marengo', 'value': 'America/Indiana/Marengo'},
    {'label': 'Indiana - Petersburg', 'value': 'America/Indiana/Petersburg'},
    {'label': 'Indiana - Vevay', 'value': 'America/Indiana/Vevay'},
    {'label': 'Chicago', 'value': 'America/Chicago'},
    {'label': 'Indiana - Tell City', 'value': 'America/Indiana/Tell_City'},
    {'label': 'Indiana - Knox', 'value': 'America/Indiana/Knox'},
    {'label': 'Menominee', 'value': 'America/Menominee'},
    {'label': 'North Dakota - Center', 'value': 'America/North_Dakota/Center'},
    {'label': 'North Dakota - New Salem', 'value': 'America/North_Dakota/New_Salem'},
    {'label': 'North Dakota - Beulah', 'value': 'America/North_Dakota/Beulah'},
    {'label': 'Denver', 'value': 'America/Denver'},
    {'label': 'Boise', 'value': 'America/Boise'},
    {'label': 'Phoenix', 'value': 'America/Phoenix'},
    {'label': 'Los Angeles', 'value': 'America/Los_Angeles'},
    {'label': 'Anchorage', 'value': 'America/Anchorage'},
    {'label': 'Juneau', 'value': 'America/Juneau'},
    {'label': 'Sitka', 'value': 'America/Sitka'},
    {'label': 'Metlakatla', 'value': 'America/Metlakatla'},
    {'label': 'Yakutat', 'value': 'America/Yakutat'},
    {'label': 'Nome', 'value': 'America/Nome'},
    {'label': 'Adak', 'value': 'America/Adak'},
    {'label': 'Montevideo', 'value': 'America/Montevideo'},
    {'label': 'St Lucia', 'value': 'America/St_Lucia'},
    {'label': 'Port of Spain', 'value': 'America/Port_of_Spain'},
    {'label': 'Grand Turk', 'value': 'America/Grand_Turk'},
    {'label': 'St Vincent', 'value': 'America/St_Vincent'},
    {'label': 'Antigua', 'value': 'America/Antigua'},
    {'label': 'Anguilla', 'value': 'America/Anguilla'},
    {'label': 'St Thomas', 'value': 'America/St_Thomas'},
    {'label': 'Argentina - Buenos Aires', 'value': 'America/Argentina/Buenos_Aires'},
    {'label': 'Argentina - Cordoba', 'value': 'America/Argentina/Cordoba'},
    {'label': 'Argentina - Salta', 'value': 'America/Argentina/Salta'},
    {'label': 'Argentina - Jujuy', 'value': 'America/Argentina/Jujuy'},
    {'label': 'Argentina - Tucuman', 'value': 'America/Argentina/Tucuman'},
    {'label': 'Argentina - Catamarca', 'value': 'America/Argentina/Catamarca'},
    {'label': 'Argentina - La Rioja', 'value': 'America/Argentina/La_Rioja'},
    {'label': 'Argentina - San Juan', 'value': 'America/Argentina/San_Juan'},
    {'label': 'Argentina - Mendoza', 'value': 'America/Argentina/Mendoza'},
    {'label': 'Argentina - San Luis', 'value': 'America/Argentina/San_Luis'},
    {'label': 'Argentina - Rio Gallegos', 'value': 'America/Argentina/Rio_Gallegos'},
    {'label': 'Argentina - Ushuaia', 'value': 'America/Argentina/Ushuaia'},
    {'label': 'Aruba', 'value': 'America/Aruba'}
  ],
  'Antarctica': [
    {'label': 'McMurdo', 'value': 'Antarctica/McMurdo'},
    {'label': 'Casey', 'value': 'Antarctica/Casey'},
    {'label': 'Davis', 'value': 'Antarctica/Davis'},
    {'label': 'DumontDUrville', 'value': 'Antarctica/DumontDUrville'},
    {'label': 'Mawson', 'value': 'Antarctica/Mawson'},
    {'label': 'Palmer', 'value': 'Antarctica/Palmer'},
    {'label': 'Rothera', 'value': 'Antarctica/Rothera'},
    {'label': 'Syowa', 'value': 'Antarctica/Syowa'},
    {'label': 'Troll', 'value': 'Antarctica/Troll'},
    {'label': 'Vostok', 'value': 'Antarctica/Vostok'},
    {'label': 'Macquarie', 'value': 'Antarctica/Macquarie'}
  ],
  'Arctic': [
    {'label': 'Longyearbyen', 'value': 'Arctic/Longyearbyen'}
  ],
  'Asia': [
    {'label': 'Dhaka', 'value': 'Asia/Dhaka'},
    {'label': 'Brunei', 'value': 'Asia/Brunei'},
    {'label': 'Bahrain', 'value': 'Asia/Bahrain'},
    {'label': 'Thimphu', 'value': 'Asia/Thimphu'},
    {'label': 'Yekaterinburg', 'value': 'Asia/Yekaterinburg'},
    {'label': 'Omsk', 'value': 'Asia/Omsk'},
    {'label': 'Novosibirsk', 'value': 'Asia/Novosibirsk'},
    {'label': 'Barnaul', 'value': 'Asia/Barnaul'},
    {'label': 'Tomsk', 'value': 'Asia/Tomsk'},
    {'label': 'Novokuznetsk', 'value': 'Asia/Novokuznetsk'},
    {'label': 'Krasnoyarsk', 'value': 'Asia/Krasnoyarsk'},
    {'label': 'Irkutsk', 'value': 'Asia/Irkutsk'},
    {'label': 'Chita', 'value': 'Asia/Chita'},
    {'label': 'Yakutsk', 'value': 'Asia/Yakutsk'},
    {'label': 'Khandyga', 'value': 'Asia/Khandyga'},
    {'label': 'Vladivostok', 'value': 'Asia/Vladivostok'},
    {'label': 'Ust-Nera', 'value': 'Asia/Ust-Nera'},
    {'label': 'Magadan', 'value': 'Asia/Magadan'},
    {'label': 'Sakhalin', 'value': 'Asia/Sakhalin'},
    {'label': 'Srednekolymsk', 'value': 'Asia/Srednekolymsk'},
    {'label': 'Kamchatka', 'value': 'Asia/Kamchatka'},
    {'label': 'Anadyr', 'value': 'Asia/Anadyr'},
    {'label': 'Dili', 'value': 'Asia/Dili'},
    {'label': 'Ashgabat', 'value': 'Asia/Ashgabat'},
    {'label': 'Dushanbe', 'value': 'Asia/Dushanbe'},
    {'label': 'Tokyo', 'value': 'Asia/Tokyo'},
    {'label': 'Tbilisi', 'value': 'Asia/Tbilisi'},
    {'label': 'Muscat', 'value': 'Asia/Muscat'},
    {'label': 'Amman', 'value': 'Asia/Amman'},
    {'label': 'Hong Kong', 'value': 'Asia/Hong_Kong'},
    {'label': 'Gaza', 'value': 'Asia/Gaza'},
    {'label': 'Hebron', 'value': 'Asia/Hebron'},
    {'label': 'Baghdad', 'value': 'Asia/Baghdad'},
    {'label': 'Karachi', 'value': 'Asia/Karachi'},
    {'label': 'Manila', 'value': 'Asia/Manila'},
    {'label': 'Ho Chi Minh', 'value': 'Asia/Ho_Chi_Minh'},
    {'label': 'Riyadh', 'value': 'Asia/Riyadh'},
    {'label': 'Samarkand', 'value': 'Asia/Samarkand'},
    {'label': 'Tashkent', 'value': 'Asia/Tashkent'},
    {'label': 'Yangon', 'value': 'Asia/Yangon'},
    {'label': 'Macau', 'value': 'Asia/Macau'},
    {'label': 'Ulaanbaatar', 'value': 'Asia/Ulaanbaatar'},
    {'label': 'Hovd', 'value': 'Asia/Hovd'},
    {'label': 'Choibalsan', 'value': 'Asia/Choibalsan'},
    {'label': 'Kuala Lumpur', 'value': 'Asia/Kuala_Lumpur'},
    {'label': 'Kuching', 'value': 'Asia/Kuching'},
    {'label': 'Jerusalem', 'value': 'Asia/Jerusalem'},
    {'label': 'Kathmandu', 'value': 'Asia/Kathmandu'},
    {'label': 'Shanghai', 'value': 'Asia/Shanghai'},
    {'label': 'Urumqi', 'value': 'Asia/Urumqi'},
    {'label': 'Nicosia', 'value': 'Asia/Nicosia'},
    {'label': 'Famagusta', 'value': 'Asia/Famagusta'},
    {'label': 'Damascus', 'value': 'Asia/Damascus'},
    {'label': 'Bishkek', 'value': 'Asia/Bishkek'},
    {'label': 'Phnom Penh', 'value': 'Asia/Phnom_Penh'},
    {'label': 'Seoul', 'value': 'Asia/Seoul'},
    {'label': 'Pyongyang', 'value': 'Asia/Pyongyang'},
    {'label': 'Kuwait', 'value': 'Asia/Kuwait'},
    {'label': 'Almaty', 'value': 'Asia/Almaty'},
    {'label': 'Qyzylorda', 'value': 'Asia/Qyzylorda'},
    {'label': 'Aqtobe', 'value': 'Asia/Aqtobe'},
    {'label': 'Aqtau', 'value': 'Asia/Aqtau'},
    {'label': 'Atyrau', 'value': 'Asia/Atyrau'},
    {'label': 'Oral', 'value': 'Asia/Oral'},
    {'label': 'Singapore', 'value': 'Asia/Singapore'},
    {'label': 'Aden', 'value': 'Asia/Aden'},
    {'label': 'Beirut', 'value': 'Asia/Beirut'},
    {'label': 'Vientiane', 'value': 'Asia/Vientiane'},
    {'label': 'Taipei', 'value': 'Asia/Taipei'},
    {'label': 'Colombo', 'value': 'Asia/Colombo'},
    {'label': 'Bangkok', 'value': 'Asia/Bangkok'},
    {'label': 'Dubai', 'value': 'Asia/Dubai'},
    {'label': 'Kabul', 'value': 'Asia/Kabul'},
    {'label': 'Tehran', 'value': 'Asia/Tehran'},
    {'label': 'Yerevan', 'value': 'Asia/Yerevan'},
    {'label': 'Kolkata', 'value': 'Asia/Kolkata'},
    {'label': 'Baku', 'value': 'Asia/Baku'},
    {'label': 'Jakarta', 'value': 'Asia/Jakarta'},
    {'label': 'Pontianak', 'value': 'Asia/Pontianak'},
    {'label': 'Makassar', 'value': 'Asia/Makassar'},
    {'label': 'Jayapura', 'value': 'Asia/Jayapura'},
    {'label': 'Qatar', 'value': 'Asia/Qatar'}
  ],
  'Atlantic': [
    {'label': 'Bermuda', 'value': 'Atlantic/Bermuda'},
    {'label': 'South Georgia', 'value': 'Atlantic/South_Georgia'},
    {'label': 'Madeira', 'value': 'Atlantic/Madeira'},
    {'label': 'Azores', 'value': 'Atlantic/Azores'},
    {'label': 'Canary', 'value': 'Atlantic/Canary'},
    {'label': 'St Helena', 'value': 'Atlantic/St_Helena'},
    {'label': 'Stanley', 'value': 'Atlantic/Stanley'},
    {'label': 'Faroe', 'value': 'Atlantic/Faroe'},
    {'label': 'Cape Verde', 'value': 'Atlantic/Cape_Verde'},
    {'label': 'Reykjavik', 'value': 'Atlantic/Reykjavik'}
  ],
  'Australia': [
    {'label': 'Lord Howe', 'value': 'Australia/Lord_Howe'},
    {'label': 'Hobart', 'value': 'Australia/Hobart'},
    {'label': 'Currie', 'value': 'Australia/Currie'},
    {'label': 'Melbourne', 'value': 'Australia/Melbourne'},
    {'label': 'Sydney', 'value': 'Australia/Sydney'},
    {'label': 'Broken Hill', 'value': 'Australia/Broken_Hill'},
    {'label': 'Brisbane', 'value': 'Australia/Brisbane'},
    {'label': 'Lindeman', 'value': 'Australia/Lindeman'},
    {'label': 'Adelaide', 'value': 'Australia/Adelaide'},
    {'label': 'Darwin', 'value': 'Australia/Darwin'},
    {'label': 'Perth', 'value': 'Australia/Perth'},
    {'label': 'Eucla', 'value': 'Australia/Eucla'}
  ],
  'Europe': [
    {'label': 'Brussels', 'value': 'Europe/Brussels'},
    {'label': 'Sofia', 'value': 'Europe/Sofia'},
    {'label': 'Sarajevo', 'value': 'Europe/Sarajevo'},
    {'label': 'Jersey', 'value': 'Europe/Jersey'},
    {'label': 'Minsk', 'value': 'Europe/Minsk'},
    {'label': 'Kaliningrad', 'value': 'Europe/Kaliningrad'},
    {'label': 'Moscow', 'value': 'Europe/Moscow'},
    {'label': 'Simferopol', 'value': 'Europe/Simferopol'},
    {'label': 'Volgograd', 'value': 'Europe/Volgograd'},
    {'label': 'Kirov', 'value': 'Europe/Kirov'},
    {'label': 'Astrakhan', 'value': 'Europe/Astrakhan'},
    {'label': 'Saratov', 'value': 'Europe/Saratov'},
    {'label': 'Ulyanovsk', 'value': 'Europe/Ulyanovsk'},
    {'label': 'Samara', 'value': 'Europe/Samara'},
    {'label': 'Belgrade', 'value': 'Europe/Belgrade'},
    {'label': 'Bucharest', 'value': 'Europe/Bucharest'},
    {'label': 'Athens', 'value': 'Europe/Athens'},
    {'label': 'Guernsey', 'value': 'Europe/Guernsey'},
    {'label': 'London', 'value': 'Europe/London'},
    {'label': 'Gibraltar', 'value': 'Europe/Gibraltar'},
    {'label': 'Zagreb', 'value': 'Europe/Zagreb'},
    {'label': 'Budapest', 'value': 'Europe/Budapest'},
    {'label': 'Lisbon', 'value': 'Europe/Lisbon'},
    {'label': 'Warsaw', 'value': 'Europe/Warsaw'},
    {'label': 'Tallinn', 'value': 'Europe/Tallinn'},
    {'label': 'Rome', 'value': 'Europe/Rome'},
    {'label': 'Madrid', 'value': 'Europe/Madrid'},
    {'label': 'Podgorica', 'value': 'Europe/Podgorica'},
    {'label': 'Chisinau', 'value': 'Europe/Chisinau'},
    {'label': 'Monaco', 'value': 'Europe/Monaco'},
    {'label': 'Skopje', 'value': 'Europe/Skopje'},
    {'label': 'Malta', 'value': 'Europe/Malta'},
    {'label': 'Isle of Man', 'value': 'Europe/Isle_of_Man'},
    {'label': 'Paris', 'value': 'Europe/Paris'},
    {'label': 'Helsinki', 'value': 'Europe/Helsinki'},
    {'label': 'Amsterdam', 'value': 'Europe/Amsterdam'},
    {'label': 'Oslo', 'value': 'Europe/Oslo'},
    {'label': 'Zurich', 'value': 'Europe/Zurich'},
    {'label': 'Prague', 'value': 'Europe/Prague'},
    {'label': 'Bratislava', 'value': 'Europe/Bratislava'},
    {'label': 'Ljubljana', 'value': 'Europe/Ljubljana'},
    {'label': 'San Marino', 'value': 'Europe/San_Marino'},
    {'label': 'Stockholm', 'value': 'Europe/Stockholm'},
    {'label': 'Copenhagen', 'value': 'Europe/Copenhagen'},
    {'label': 'Berlin', 'value': 'Europe/Berlin'},
    {'label': 'Busingen', 'value': 'Europe/Busingen'},
    {'label': 'Istanbul', 'value': 'Europe/Istanbul'},
    {'label': 'Vaduz', 'value': 'Europe/Vaduz'},
    {'label': 'Riga', 'value': 'Europe/Riga'},
    {'label': 'Vilnius', 'value': 'Europe/Vilnius'},
    {'label': 'Luxembourg', 'value': 'Europe/Luxembourg'},
    {'label': 'Vatican', 'value': 'Europe/Vatican'},
    {'label': 'Andorra', 'value': 'Europe/Andorra'},
    {'label': 'Tirane', 'value': 'Europe/Tirane'},
    {'label': 'Vienna', 'value': 'Europe/Vienna'},
    {'label': 'Mariehamn', 'value': 'Europe/Mariehamn'},
    {'label': 'Dublin', 'value': 'Europe/Dublin'},
    {'label': 'Kiev', 'value': 'Europe/Kiev'},
    {'label': 'Uzhgorod', 'value': 'Europe/Uzhgorod'},
    {'label': 'Zaporozhye', 'value': 'Europe/Zaporozhye'}
  ],
  'Indian': [
    {'label': 'Reunion', 'value': 'Indian/Reunion'},
    {'label': 'Antananarivo', 'value': 'Indian/Antananarivo'},
    {'label': 'Mauritius', 'value': 'Indian/Mauritius'},
    {'label': 'Maldives', 'value': 'Indian/Maldives'},
    {'label': 'Chagos', 'value': 'Indian/Chagos'},
    {'label': 'Cocos', 'value': 'Indian/Cocos'},
    {'label': 'Christmas', 'value': 'Indian/Christmas'},
    {'label': 'Comoro', 'value': 'Indian/Comoro'},
    {'label': 'Mahe', 'value': 'Indian/Mahe'},
    {'label': 'Mayotte', 'value': 'Indian/Mayotte'},
    {'label': 'Kerguelen', 'value': 'Indian/Kerguelen'}
  ],
  'Pacific': [
    {'label': 'Wallis', 'value': 'Pacific/Wallis'},
    {'label': 'Apia', 'value': 'Pacific/Apia'},
    {'label': 'Fakaofo', 'value': 'Pacific/Fakaofo'},
    {'label': 'Guam', 'value': 'Pacific/Guam'},
    {'label': 'Palau', 'value': 'Pacific/Palau'},
    {'label': 'Tahiti', 'value': 'Pacific/Tahiti'},
    {'label': 'Marquesas', 'value': 'Pacific/Marquesas'},
    {'label': 'Gambier', 'value': 'Pacific/Gambier'},
    {'label': 'Port Moresby', 'value': 'Pacific/Port_Moresby'},
    {'label': 'Bougainville', 'value': 'Pacific/Bougainville'},
    {'label': 'Pitcairn', 'value': 'Pacific/Pitcairn'},
    {'label': 'Galapagos', 'value': 'Pacific/Galapagos'},
    {'label': 'Guadalcanal', 'value': 'Pacific/Guadalcanal'},
    {'label': 'Majuro', 'value': 'Pacific/Majuro'},
    {'label': 'Kwajalein', 'value': 'Pacific/Kwajalein'},
    {'label': 'Saipan', 'value': 'Pacific/Saipan'},
    {'label': 'Fiji', 'value': 'Pacific/Fiji'},
    {'label': 'Chuuk', 'value': 'Pacific/Chuuk'},
    {'label': 'Pohnpei', 'value': 'Pacific/Pohnpei'},
    {'label': 'Kosrae', 'value': 'Pacific/Kosrae'},
    {'label': 'Efate', 'value': 'Pacific/Efate'},
    {'label': 'Noumea', 'value': 'Pacific/Noumea'},
    {'label': 'Norfolk', 'value': 'Pacific/Norfolk'},
    {'label': 'Auckland', 'value': 'Pacific/Auckland'},
    {'label': 'Chatham', 'value': 'Pacific/Chatham'},
    {'label': 'Nauru', 'value': 'Pacific/Nauru'},
    {'label': 'Niue', 'value': 'Pacific/Niue'},
    {'label': 'Rarotonga', 'value': 'Pacific/Rarotonga'},
    {'label': 'Easter', 'value': 'Pacific/Easter'},
    {'label': 'Tarawa', 'value': 'Pacific/Tarawa'},
    {'label': 'Enderbury', 'value': 'Pacific/Enderbury'},
    {'label': 'Kiritimati', 'value': 'Pacific/Kiritimati'},
    {'label': 'Honolulu', 'value': 'Pacific/Honolulu'},
    {'label': 'Johnston', 'value': 'Pacific/Johnston'},
    {'label': 'Midway', 'value': 'Pacific/Midway'},
    {'label': 'Wake', 'value': 'Pacific/Wake'},
    {'label': 'Funafuti', 'value': 'Pacific/Funafuti'},
    {'label': 'Tongatapu', 'value': 'Pacific/Tongatapu'},
    {'label': 'Pago Pago', 'value': 'Pacific/Pago_Pago'}
  ]
}
